/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as SubmitFilmRouteImport } from './routes/submit-film'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCommandCenterRouteImport } from './routes/admin.command-center'
import { Route as AdminCustomizationRouteImport } from './routes/admin.customization'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminTitlesRouteImport } from './routes/admin.titles'
import { Route as OwnerSharingRouteImport } from './routes/owner.sharing'
import { Route as OwnerSupplyChainRouteImport } from './routes/owner.supply-chain'
import { Route as OwnerTransfersRouteImport } from './routes/owner.transfers'
import { Route as OwnerWorkspaceRouteImport } from './routes/owner.workspace'
import { Route as TitleSlugRouteImport } from './routes/title.$slug'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitFilmRoute = SubmitFilmRouteImport.update({
  id: '/submit-film',
  path: '/submit-film',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommandCenterRoute = AdminCommandCenterRouteImport.update({
  id: '/admin/command-center',
  path: '/admin/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomizationRoute = AdminCustomizationRouteImport.update({
  id: '/admin/customization',
  path: '/admin/customization',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTitlesRoute = AdminTitlesRouteImport.update({
  id: '/admin/titles',
  path: '/admin/titles',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSharingRoute = OwnerSharingRouteImport.update({
  id: '/owner/sharing',
  path: '/owner/sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSupplyChainRoute = OwnerSupplyChainRouteImport.update({
  id: '/owner/supply-chain',
  path: '/owner/supply-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerTransfersRoute = OwnerTransfersRouteImport.update({
  id: '/owner/transfers',
  path: '/owner/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerWorkspaceRoute = OwnerWorkspaceRouteImport.update({
  id: '/owner/workspace',
  path: '/owner/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleSlugRoute = TitleSlugRouteImport.update({
  id: '/title/$slug',
  path: '/title/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/browse': typeof BrowseRoute
  '/kids': typeof KidsRoute
  '/login': typeof LoginRoute
  '/my-list': typeof MyListRoute
  '/plans': typeof PlansRoute
  '/submit-film': typeof SubmitFilmRoute
  '/admin/command-center': typeof AdminCommandCenterRoute
  '/admin/customization': typeof AdminCustomizationRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/titles': typeof AdminTitlesRoute
  '/owner/sharing': typeof OwnerSharingRoute
  '/owner/supply-chain': typeof OwnerSupplyChainRoute
  '/owner/transfers': typeof OwnerTransfersRoute
  '/owner/workspace': typeof OwnerWorkspaceRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/browse': typeof BrowseRoute
  '/kids': typeof KidsRoute
  '/login': typeof LoginRoute
  '/my-list': typeof MyListRoute
  '/plans': typeof PlansRoute
  '/submit-film': typeof SubmitFilmRoute
  '/admin/command-center': typeof AdminCommandCenterRoute
  '/admin/customization': typeof AdminCustomizationRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/titles': typeof AdminTitlesRoute
  '/owner/sharing': typeof OwnerSharingRoute
  '/owner/supply-chain': typeof OwnerSupplyChainRoute
  '/owner/transfers': typeof OwnerTransfersRoute
  '/owner/workspace': typeof OwnerWorkspaceRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/browse': typeof BrowseRoute
  '/kids': typeof KidsRoute
  '/login': typeof LoginRoute
  '/my-list': typeof MyListRoute
  '/plans': typeof PlansRoute
  '/submit-film': typeof SubmitFilmRoute
  '/admin/command-center': typeof AdminCommandCenterRoute
  '/admin/customization': typeof AdminCustomizationRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/titles': typeof AdminTitlesRoute
  '/owner/sharing': typeof OwnerSharingRoute
  '/owner/supply-chain': typeof OwnerSupplyChainRoute
  '/owner/transfers': typeof OwnerTransfersRoute
  '/owner/workspace': typeof OwnerWorkspaceRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/browse'
    | '/kids'
    | '/login'
    | '/my-list'
    | '/plans'
    | '/submit-film'
    | '/admin/command-center'
    | '/admin/customization'
    | '/admin/plans'
    | '/admin/revenue'
    | '/admin/titles'
    | '/owner/sharing'
    | '/owner/supply-chain'
    | '/owner/transfers'
    | '/owner/workspace'
    | '/title/$slug'
    | '/watch/$slug'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/browse'
    | '/kids'
    | '/login'
    | '/my-list'
    | '/plans'
    | '/submit-film'
    | '/admin/command-center'
    | '/admin/customization'
    | '/admin/plans'
    | '/admin/revenue'
    | '/admin/titles'
    | '/owner/sharing'
    | '/owner/supply-chain'
    | '/owner/transfers'
    | '/owner/workspace'
    | '/title/$slug'
    | '/watch/$slug'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/browse'
    | '/kids'
    | '/login'
    | '/my-list'
    | '/plans'
    | '/submit-film'
    | '/admin/command-center'
    | '/admin/customization'
    | '/admin/plans'
    | '/admin/revenue'
    | '/admin/titles'
    | '/owner/sharing'
    | '/owner/supply-chain'
    | '/owner/transfers'
    | '/owner/workspace'
    | '/title/$slug'
    | '/watch/$slug'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BrowseRoute: typeof BrowseRoute
  KidsRoute: typeof KidsRoute
  LoginRoute: typeof LoginRoute
  MyListRoute: typeof MyListRoute
  PlansRoute: typeof PlansRoute
  SubmitFilmRoute: typeof SubmitFilmRoute
  AdminCommandCenterRoute: typeof AdminCommandCenterRoute
  AdminCustomizationRoute: typeof AdminCustomizationRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminTitlesRoute: typeof AdminTitlesRoute
  OwnerSharingRoute: typeof OwnerSharingRoute
  OwnerSupplyChainRoute: typeof OwnerSupplyChainRoute
  OwnerTransfersRoute: typeof OwnerTransfersRoute
  OwnerWorkspaceRoute: typeof OwnerWorkspaceRoute
  TitleSlugRoute: typeof TitleSlugRoute
  WatchSlugRoute: typeof WatchSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-film': {
      id: '/submit-film'
      path: '/submit-film'
      fullPath: '/submit-film'
      preLoaderRoute: typeof SubmitFilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/command-center': {
      id: '/admin/command-center'
      path: '/admin/command-center'
      fullPath: '/admin/command-center'
      preLoaderRoute: typeof AdminCommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customization': {
      id: '/admin/customization'
      path: '/admin/customization'
      fullPath: '/admin/customization'
      preLoaderRoute: typeof AdminCustomizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/titles': {
      id: '/admin/titles'
      path: '/admin/titles'
      fullPath: '/admin/titles'
      preLoaderRoute: typeof AdminTitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/sharing': {
      id: '/owner/sharing'
      path: '/owner/sharing'
      fullPath: '/owner/sharing'
      preLoaderRoute: typeof OwnerSharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/supply-chain': {
      id: '/owner/supply-chain'
      path: '/owner/supply-chain'
      fullPath: '/owner/supply-chain'
      preLoaderRoute: typeof OwnerSupplyChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/transfers': {
      id: '/owner/transfers'
      path: '/owner/transfers'
      fullPath: '/owner/transfers'
      preLoaderRoute: typeof OwnerTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/workspace': {
      id: '/owner/workspace'
      path: '/owner/workspace'
      fullPath: '/owner/workspace'
      preLoaderRoute: typeof OwnerWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$slug': {
      id: '/title/$slug'
      path: '/title/$slug'
      fullPath: '/title/$slug'
      preLoaderRoute: typeof TitleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BrowseRoute: BrowseRoute,
  KidsRoute: KidsRoute,
  LoginRoute: LoginRoute,
  MyListRoute: MyListRoute,
  PlansRoute: PlansRoute,
  SubmitFilmRoute: SubmitFilmRoute,
  AdminCommandCenterRoute: AdminCommandCenterRoute,
  AdminCustomizationRoute: AdminCustomizationRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminTitlesRoute: AdminTitlesRoute,
  OwnerSharingRoute: OwnerSharingRoute,
  OwnerSupplyChainRoute: OwnerSupplyChainRoute,
  OwnerTransfersRoute: OwnerTransfersRoute,
  OwnerWorkspaceRoute: OwnerWorkspaceRoute,
  TitleSlugRoute: TitleSlugRoute,
  WatchSlugRoute: WatchSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
